AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Comparison Lambda
Resources:
    ComparisonLambda:
        Type: 'AWS::Serverless::Function'
        Properties:
          Handler: lambda_function.lambda_handler
          Runtime: pyhton3.6
          CodeUri: .
          Description: 'Lambda function for comparison'
          MemorySize: 128
          Timeout: 30
          Role: '
          #This next bit defines the API gateway
          Events:
            getAZsAPI:
              Type: Api
              Properties:
                Path: /getazs
                Method: get
          Environment:
            Variables:
              #add variables used in the code here
              REGION: eu-west-2
